### ISSUE TITLE
Non-faction soldiers no AP

### ISSUE THREAD

**Issue by CeyowenCt** [long-war-2/lwotc#82]
Non-faction soldiers have no AP, and cannot use the XCOM AP to purchase new abilities.  This is true even after the Training Facility is built.

**Comment by pledbrook** [comment]
They should get 3AP per rank. Is that not happening? I did see sergeants with 9AP, but that may only have been because I used the cheat console to rank them up. Although I don't understand why that wouldn't happen for normal rank ups too.

**Comment by CeyowenCt** [comment]
I am able to choose 1 ability at level up and that's it. For what it's worth, the ability screen looks like LW2 and not WOTC. There are no visual cues that the AP system is active for regular soldiers at all.

**Comment by pledbrook** [comment]
You should be able to see how many AP a soldier has in the armoury screen, next to the bond status. Or at least, you will be able to see it once the Training Center has been built. Are they all showing 0AP?

**Comment by CeyowenCt** [comment]
I'll take some screenshots next time I launch, but there is literally nothing related to AP. They don't have a combat intelligence rating (faction soldiers do), there is no space where AP would even show.

**Comment by SirMrMister** [comment]
@CeyowenCt Are you using any other mod besides LWOTC?

**Comment by jmartinez989** [comment]
I can confirm this is happening. All of my non faction soldiers do not have any AP. Though to be perfectly honest, I would be ok if non faction soldiers could not get AP. I can see some REALLY broken combinations of abilities for soldiers that were not intended when the LW2 classes were implemented.

**Comment by ansabalirai** [comment]
I thought adding "+bAllowAWCAbilities=true" in the class data ini would solve this? Bonus AP from flanks etc in tactical should also be appearing? I can also see the color coded icon in the detailed solider list showing their combat intelligence
Having to train abilities in the training center is another question, since even after building one, I was not able to train them. Please also see and comment in #23 for more of a balance discussion

**Comment by jmartinez989** [comment]
> I thought adding "+bAllowAWCAbilities=true" in the class data ini would solve this? Bonus AP from flanks etc in tactical should also be appearing? I can also see the color coded icon in the detailed solider list showing their combat intelligence
> Having to train abilities in the training center is another question, since even after building one, I was not able to train them. Please also see and comment in #23 for more of a balance discussion

yeah I think you are right. To be honest though not sure how to make a balanced implementation of ability points because I can see some super broken combination of abilities that would make to many soldiers too cross functional. I think the way LW2 originally did the AWC is better than the AP system TBH.

**Comment by ansabalirai** [comment]
If we have both training time and AP requirement for training extra skills and draw them from the same restrictive pool as LW2 (meaning not all perks are available for all classes), then I am not sure if the broken combinations would occur. The same AWC perks as in LW2 would be available to all classes in the training center, they would require the correct rank, they would still take time to train and if anything, the AP requirement would act as an additional filter on top (so that you need to have sufficient rank, sufficient AP and then invest enough time to train the same ability). The only difference could be that since a combination of AP and time is required, the training times can be reduced correspondingly. 
Of course, it is likely that xcom has a lot of AP due to large number of missions done (hard to say until we do an extended campaign) and so the AP requirement is met most of the time, in which case you default to LW2 behavior. In any case, it would be good to have a sink for APs gathered from missions besides just faction soldier(s).

BTW, I think there are no new perks introduced in WOTC for base classes in training center compared to LW2 AWC skills, except maybe tactical rigging?

**Comment by jmartinez989** [comment]
> If we have both training time and AP requirement for training extra skills and draw them from the same restrictive pool as LW2 (meaning not all perks are available for all classes), then I am not sure if the broken combinations would occur. The same AWC perks as in LW2 would be available to all classes in the training center, they would require the correct rank, they would still take time to train and if anything, the AP requirement would act as an additional filter on top (so that you need to have sufficient rank, sufficient AP and then invest enough time to train the same ability). The only difference could be that since a combination of AP and time is required, the training times can be reduced correspondingly.
> Of course, it is likely that xcom has a lot of AP due to large number of missions done (hard to say until we do an extended campaign) and so the AP requirement is met most of the time, in which case you default to LW2 behavior. In any case, it would be good to have a sink for APs gathered from missions besides just faction soldier(s).
> 
> BTW, I think there are no new perks introduced in WOTC for base classes in training center compared to LW2 AWC skills, except maybe tactical rigging?

Ahh ok well that is much better than current WotC implementation. Right now if it were to go in the way it is I could see classes like gunner getting perks for suppression spec but also see them getting things for shooter spec like chain shot and hail of bullets and demolish. 

I'm basically trying to cut from soldiers being able to pick skills from all trees. If they have to choose from other skills that are not in their tree for like pistol skills or something then that would be ok.

**Comment by CeyowenCt** [comment]
> I thought adding "+bAllowAWCAbilities=true" in the class data ini would solve this? Bonus AP from flanks etc in tactical should also be appearing? I can also see the color coded icon in the detailed solider list showing their combat intelligence
> Having to train abilities in the training center is another question, since even after building one, I was not able to train them. Please also see and comment in #23 for more of a balance discussion

So this appears to help!  I changed it in just the Technical as a test, and as you can see in the screenshot my Techs now have Combat Intelligence and AP (although it appears they start with 0 after this code is added).  In order to train abilities I have to go to the training center and choose the soldier there, cannot be done from the Barracks.

[Screenshot](https://steamuserimages-a.akamaihd.net/ugc/966494366426937832/B571949F28C8224481E82CCB225A1D5D03D87221/)

**Comment by pledbrook** [comment]
The Tab key giving levels to soldiers is apparently a debug feature in the community highlander. Although I don't understand why you would be experiencing it. I thought I built a release version of the mod. I'll need to verify what happens for the next release to make sure it's not a debug version.

**Comment by pledbrook** [comment]
I should probably remove the code that does that in `UIArmory_Promotion`.

BTW, can I close this now? I suggest opening another issue if you want to report any of the things you mentioned above.

**Comment by CeyowenCt** [comment]
Would launch commands (added to the .exe) possibly cause the debug features?  I may still have those enabled from long ago, and I do also get some white text detailing event triggers on tactical map (i.e. concealment loss, turn timer decrease).  I didn't think that was from LWOTC but I haven't looked into it.

And yes I believe the AP issue is resolved!  Just requires adding "+bAllowAWCAbilities=true" to each class in the XComClassData.ini - I added it before the "+BaseAbilityPointsPerPromotion=3" line.

**Comment by pledbrook** [comment]
I was seeing those event triggers in missions too, even with the "release" version of the mod. I didn't really understand why. Still don't. I suspect that something didn't work quite as I expected when I built the release.
