### ISSUE TITLE
Segmentation Error (11) when Launching Missions.

### ISSUE THREAD

**Issue by CrazyKing508** [long-war-2/lwotc#829]
The game crashes when trying to start certain missions.  I believe this may be a Linux issue. I am only using the essential mods. I will attach my save game to this issue. 
[save_Save 12.zip](https://github.com/long-war-2/lwotc/files/4008527/save_Save.12.zip)

**Comment by belathus** [comment]
I'm having a similar issue. Every time I try loading the Smash and Grab mission, the game crashes.
[Campaign 54, Mission 16.zip](https://github.com/long-war-2/lwotc/files/4008583/Campaign.54.Mission.16.zip).

**Comment by salierisghost** [comment]
Any chance you can provide the log files for the crash?

**Comment by CrazyKing508** [comment]
Are you talking about the crash files.  If not I will happily recreate the crash and find the log file. 

[34073140-b71c-a114-31c4ff43-4972504d.zip](https://github.com/long-war-2/lwotc/files/4008833/34073140-b71c-a114-31c4ff43-4972504d.zip)

**Comment by rootfuchs** [comment]
Same Problem here. I'm using Linux too. For me the rescue Haven-Personell-Missions are crashing with Segfault every time. I'll try to recreate the setup with debugmode and logging on.

**Comment by maldun** [comment]
Hey there! @CrazyKing508 I think I already saw your problem on reddit. I tried now your savegame but I couldn't reproduce your error. I also had the recommended mods added: https://steamcommunity.com/sharedfiles/filedetails/?id=1878558598
Can you try to activate these also? I could imagine that maybe unintentional something from these mods is missing.

If that's not the problem, can you be more specific of your setup? I'm running on Fedora 29 with Kernel 5.1 and closed source NVidia drivers. What distro do you use? If disabling the mods does not cause the problem it's more likely that it's something with your machine/setup/system

**Comment by maldun** [comment]
@belathus I couldn't also reproduce your crash on my machine. Can you give specifics of your setup, and maybe logs of your crash.
I don't think it's a general Linux issue more something miss-configured. Could you also check your mods? I only activated recommended and essential mods: https://steamcommunity.com/sharedfiles/filedetails/?id=1921971985
https://steamcommunity.com/sharedfiles/filedetails/?id=1878558598

I don't know if I can help but I will try

**Comment by zygny** [comment]
@maldun , another linux (arch, kernel 5.4.10, using steam-runtime) user here with the same issue...
I did the following:
 - unsubscribe all
 - steam verify (all DLC enabled)
 - re-add highlander and lwotc in defaultmodoptions.ini
 - subscribe to the 'required mods' collection (and nothing else)
 - delete all configs and profile.bin
 - play through until I got to the segmentation error
 - delete all "Suppress=*" lines from XComEngine.ini, retry loading the save
[Launch.log](https://github.com/long-war-2/lwotc/files/4050136/Launch.log)
 - add the 'recommended' mods collection (still fails)

In this case its a Jailbreak mission, but I have started a few campaigns and it can be multiple mission types
Save: (next mission to 100% infiltrate triggers the fault)
[save_AUTOSAVE- Campaign 16, Mission 5_1.zip](https://github.com/long-war-2/lwotc/files/4050151/save_AUTOSAVE-.Campaign.16.Mission.5_1.zip)


Things I have observed:
 - trying @belathus save (Campaign 54, Mission 16.zip) I can reproduce the crash, trying @CrazyKing508  save (save_Save 12.zip) the mission loads fine for me too.
 - the crash is right before the 'launch' screen right before the mission starts
 - aborting the mission and carrying on works - the campaign is not completely bugged, other missions will have the segmentation fault though

Hope this helps...

**Comment by Ziktofel** [comment]
Can it be realted to https://github.com/long-war-2/lwotc/issues/733?

**Comment by maldun** [comment]
Hi again! I updated my system today to Fedora 31 and voilà the segfaultappears ... this was with
Kernel version kernel-5.4.8 and nvidia driver NVIDIA-Linux-x86_64-440.44.run

Going back to kernel-5.1.11 and nvidia driver NVIDIA-Linux-x86_64-430.26.run works fine
so as I suspected a driver issue. I suspect it has something to do with the 32-bit libraries

**Comment by zygny** [comment]
Interesting, shouldn't be graphics drivers then (I am using an AMD Vega 56), I'll see what I can downgrade/test tonight

**Comment by Ziktofel** [comment]
I had nvidia drivers v 430.xx and observed the crash (upgraded to 440 and crashes too), but I have Linux 5.3.x all the time. I think that the kernel should be one making the issue

**Comment by millertimebjm** [comment]
Getting the same error:
5.4.12-1-MANJARO
![Screenshot_2020-01-19_16-35-37-cropped](https://user-images.githubusercontent.com/10730465/72684193-146da900-3aa4-11ea-9cb4-e7eb0f6f6daa.png)

[dump.zip](https://github.com/long-war-2/lwotc/files/4082891/dump.zip)

Let me know if any more information is useful.

**Comment by zygny** [comment]
Hi all, sorry I didn't get back earlier - had an OS drive failure and got distracted by other rabbit-holes.
On reinstall, I am no longer encountering the issue... 
I made a test campaign last night and launched 10 missions (just throwing the flare on first turn/running to the evac point) without any problems.

My only guess is I did eventually notice I still had steam-cloud-sync enabled so it was restoring my 'profile.bin' in the saves directory every time I started XCOM, so I disabled cloud-sync before installing XCOM this time.
Otherwise I just screwed up the installation multiple times and finally got it right this time??

**Comment by zygny** [comment]
(Not sure if I am providing useful input or just derailing things?)

Started a non-testing campaign, have been getting semi-regular seg-faults, all but one were solved by just deleting profile.bin and loading the last autosave. The one that did persist (unfortunately I didn't make a save of it) I just aborted the mission and was able to continue the campaign fine (was lib2 too!).

Does this solve (most) issues for others? Is this primarily an issue around writing to profile.bin and corrupting it?

**Comment by Aurelicornus** [comment]
> (Not sure if I am providing useful input or just derailing things?)
> 
> Started a non-testing campaign, have been getting semi-regular seg-faults, all but one were solved by just deleting profile.bin and loading the last autosave. The one that did persist (unfortunately I didn't make a save of it) I just aborted the mission and was able to continue the campaign fine (was lib2 too!).
> 
> Does this solve (most) issues for others? Is this primarily an issue around writing to profile.bin and corrupting it?

I experience the same issue on Linux, and I can confirm that delete the profile.bin file under the save folder fix the seg-faults for the ongoing campaign.
Seems a linux only relate issue, and only when LwotC is running, because this never happened to me with base WotC and with vanilla Xcom 2+ Long War (heavily modded)

**Comment by JohanAke1** [comment]
This is happening to me also, game crashes when starting one of the earliest missions. I'm on Ubuntu 19.04.
Game crashed with signal SIGSEGV(11): Segmentation fault.

Tried deleting the profile.bin but that did not help me... I have updated the mod to the newest but no affect, still crashing.

**Comment by belathus** [comment]
Still getting this crash myself, even after several OS updates. Deleting profile.bin saved a mission once, but I had to cancel at least 3 missions now, where deleting profile.bin didn't help. Twice in a row now on freeing captured rebels. I was able to get the mission to run once, but haven't been able to since.

I tried removing all but the essential mods, but I still get the crash on occasion. I really want to play LWotC, but these crashes are discouraging.

**Comment by Aurelicornus** [comment]
Indeed the crash get back to appear to me too, despite deleting the file worked once. I have an ATI card with open-source drivers and a Ryzen 2700 CPU, but I wonder if is a crash related to the Linux port than the system itself.
Is strange because with Long War on vanilla Xcom 2 never got these issues. Seems the culprit lies in something within the rescue rebel and VIP missions, because my crashes happens all time with one of those.

**Comment by Ziktofel** [comment]
Encountered this again. Can anyone reproduce?

Save:
[save_Save 74.zip](https://github.com/long-war-2/lwotc/files/5646801/save_Save.74.zip)

Dump in case reporting to Feral:
[4780b441-401e-ec25-726335cf-3dffc89e.dmp.zip](https://github.com/long-war-2/lwotc/files/5646795/4780b441-401e-ec25-726335cf-3dffc89e.dmp.zip)

**Comment by Ziktofel** [comment]
Also got in FileIO.log:
```
[1426.83] XCom_Maps: , Plot_CTY_Council_MdObj_Plaza, Xenoform, 38.79
```
When browsing backups (generating the mission) I got this:
```
[2322.41] Warning: Error in Parcel/Mission Generation!
Could not find a valid objective parcel.
Using:
 Mission: RescueVIP_LW
 Plot Map: Plot_CTY_Council_MdObj_Plaza
```

**Comment by maldun** [comment]
@Ziktofel I tested your savegame. It worked fine for me.
I am on Fedora 33 Kernel 5.9.14  
and NVIDIA-Linux-x86_64-455.45.01

**Comment by maldun** [comment]
@Ziktofel Hi again! I am an idiot ... the problem was I missed to activate the Highlander mod when mod switching ...
Your save works for me. Maybe you should also check mod settings. Also Kernel is always a good start as we already found out

**Comment by maldun** [comment]
@Ziktofel Could it be related to this?:

> Map Mod Compatibility:
> 
> Map mods are just not compatible at the moment. It appears that most if not all have been abandoned or are no longer under development. So it is unlikely that they will ever be made compatible. Under no circumstances use a map pack that requires **Missing Packages Fix - Parcels and Maps Edition** or Doctor Mandarb's Map Pack they will cause you to generate a mission that will cause a hard crash in the game 100% of the time as long as you are trying to run the game with those map packs enabled.

https://github.com/long-war-2/lwotc/wiki/Mod-compatibility-%28community-maintained%29

**Comment by FilipeMatteoli** [comment]
So anyone figured out a way to fix this? I am getting this error in LWOTC, removing .bin did not help, nor disabling mods. I use ubuntu 18.04 nvidia 450, game was running flawlessly until this started to happen now I cannot get rid of it. I guess emailing the issue to Feral is not an option as we are not running the vanilla game.

**Comment by p0m1d0rka** [comment]
have same problem
tried:
delete `~/.local/share/feral-interactive/XCOM 2 WotC/VFS/Local/my games/XCOM2 War of the Chosen/XComGame/SaveData/profile.bin
`
delete `~/.local/share/feral-interactive/XCOM 2 WotC/VFS/Local/my games/XCOM2 War of the Chosen/XComGame/Config/*`

game still crashed.




Ubuntu 20.04, 
card:
`VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Tobago PRO [Radeon R7 360 / R9 360 OEM] `
driver `amdgpu-pro-20.30-1109583-ubuntu-20.04`

savefile 
[save_crash_mission.zip](https://github.com/long-war-2/lwotc/files/5921043/save_crash_mission.zip)

Looks like map issue

**Comment by Z-e-k** [comment]
Hi there, found a solution for me :
https://steamcommunity.com/workshop/filedetails/discussion/1140305914/2641874742501027600/

Problem cames from file : 
FX_Billboards.upk

hopes it will help

**Comment by cmyka1b2c3d4** [comment]
You can also run LWOTC through Proton, this has proven to be far more stable than simply using the native Feral build for me. It no longer segfaults 3 missions in. Though I have yet to complete a full campaign.

**Comment by pledbrook** [comment]
Closing this as it doesn't seem like there's anything we can do about it. Folks are welcome to keep the discussion going.

**Comment by QuantumTim** [comment]
Just run into this problem as well - also on Linux (Debian-based) - with a City Centre supply crate extraction. I was able to play the mission by switching to playing via Proton, but it was a bit of a faff, and I'll need to tweak my mod manager script a bit to work with it, though I'll probably just keep playing natively and switch to Proton just for missions that don't work.

As for some of the other saves linked above:
- @CrazyKing508's [original save](https://github.com/long-war-2/lwotc/issues/829#issue-543554562) works fine for me.
- @belathus's [save](https://github.com/long-war-2/lwotc/issues/829#issuecomment-569543648) crashes.
- @zygny's [save](https://github.com/long-war-2/lwotc/issues/829#issuecomment-573377542) also crashes.

I'm not using any map mods, so should just be stuff from the base game + LWotC itself, and I didn't have a single crash on the vanilla WotC campaign that I just completed (which also used a fair number of the same QoL mods).

I'm happy to do some further testing, but not really sure what to try. I've tried turning on logging (removing all the `Suppress=` lines from `XComEngine.ini`) but can't see anything obvious in there. The game seems to crash after a bunch of `DevStreaming: LoadPackageAsync` logs, but the last entry isn't the same between different buggy saves (though it looks fairly consistent from reloading the same save). But if the loading is actually "async" and the logs aren't, then the bad package might be logged well above where it causes the crash (if indeed that's what's causing the crash).

I don't suppose there's some way to force the game to try loading a particular package file into a map or something and then just try each of them in turn?

**Comment by FD4A** [comment]
Hello. I'm also have that problem on ubuntu 18-20 with different Nvidia drivers. Game crash on launching the mission, the map is
"City Center". If there is no fix, maybe someone know how delete or replace this map? Will it help?

**Comment by aslhdyt** [comment]
https://github.com/long-war-2/lwotc/issues/829#issuecomment-1017808777
this one working for me. 
from linux mint 20.3, ryzen7 5000 laptop with integrated radeon graphic

for me is map lg_GeneClinic_01_LW, XComMaps.ini at first comment/removing doesnt work. 
need to modify  XComParcels.ini also, remove line containing lg_GeneClinic_01_LW.

**Comment by maldun** [comment]
Fedora 37 on Kernel 6.0.12 with Both GeForce 750 Ti  and Radeaon RX 6600 and Ryzen 9 5900X.

I think I found the culprit in for my crashes in Jailbreak missions:

The line 

```
+arrAllParcelDefinitions=(MapName="lg_GeneClinic_01_LW", eSize=eParcelSizeType_Large, arrPlotTypes[0]=(strPlotType="CityCenter"), eFacing=EParcelFacingType_N, ObjectiveTags[0]="Jailbreak_LW", ObjectiveTags[1]="SmashNGrab_LW", bAllowNonObjectiveOverride=false)
```

(line 34 in XComParcels.ini, in the file `~/.local/share/Steam/steamapps/workshop/content/268500/2683996590/Config/` ) has to be removed or commented out. I will open a new issue as this is clearly a problem with assets of the mod.
